parameters:
    links:
      - "https://rnrsystems.in/"
      - "https://rnrsystems.in/about/"
      - "https://rnrsystems.in/services/"
      - "https://rnrsystems.in/projection-systems/"
      - "https://rnrsystems.in/creativehoardings/"
      - "https://rnrsystems.in/contact/"
      - "https://rnrsystems.in/privacy-policy-2/"
      - "https://rnrsystems.in/disclaimer/"
      - "https://rnrsystems.in/terms-condidtions/"
      - "https://rnrsystems.in/outdoor-led-displays/"
      - "https://rnrsystems.in/indoor-led-displays/"
      - "https://rnrsystems.in/transparent-flexible-led-displays/"
      - "https://rnrsystems.in/mobile-led-displays/"
      - "https://rnrsystems.in/led-standees/"
      - "https://rnrsystems.in/led-screen-rentals/"
